
package vista;


public class FormInterfaz extends javax.swing.JFrame {

    public FormInterfaz() {
        frameInit();
        this.setTitle("Sistema Parqueadero");
        this.setSize(1170, 670);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
  @SuppressWarnings("unchecked")
    private void jComboBox_tipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipoVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tipoVehiculoActionPerformed

    private void jTextField_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PlacaActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jTextField_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_busquedaActionPerformed

    private void jTextField_PlacaRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PlacaRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PlacaRetiroActionPerformed

    private void jButton_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_retirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_retirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_buscarPlacaRetiro;
    private javax.swing.JButton jButton_registrar1;
    private javax.swing.JButton jButton_retirar;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JComboBox<String> jComboBox_tipoVehiculo;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_horaEntrada;
    private javax.swing.JLabel jLabel_horaSalida;
    private javax.swing.JLabel jLabel_valorPagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_historial;
    private javax.swing.JPanel jPanel_regirstrarVehiculo;
    private javax.swing.JPanel jPanel_retirarVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_vehiculos;
    private javax.swing.JTextField jTextField_Placa;
    private javax.swing.JTextField jTextField_PlacaRetiro;
    private javax.swing.JTextField jTextField_busqueda;
    // End of variables declaration//GEN-END:variables

}
